### ISSUE TITLE
Flashlight battery is draining even though the light is off

### ISSUE THREAD

**Issue by willparsons** [redassser/Lc-Flashlight#1]
It seems like there's a weird edge case where the flashlight is off but draining the battery.

When you put the flashlight in the cabinet you can see that it's switching state, not sure if this is just the game itself though.

**Comment by rpiedev** [comment]
I'll have to look into that flashlight off but draining battery thing, I'm not sure why that would happen.

The switching when putting in a cabinet is definitely a game thing though, very weird bug that I've seen on vanilla.

**Comment by rpiedev** [comment]
I haven't been able to reproduce yet on my own so I can't act on it, but if you or anyone else can figure it out, be sure to let me know!

**Comment by willparsons** [comment]
I'll try and reproduce it
