### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by MaStErDias** [redassser/Lc-Flashlight#4]
The console displays the following error, but I definitely downloaded version 1.4.1 from the thunderstor website, but the console says that version 1.4.0 is being downloaded. (Sorry for Google translate, my English is bad)

![image](https://github.com/redassser/Lc-Flashlight/assets/118676262/2d1cb33a-bf6f-4d28-844a-1c8f3cdcff90)

**Comment by Diegugo** [comment]
The same happens with the walkie use mod
![image](https://github.com/redassser/Lc-Flashlight/assets/153622114/18dd6412-856f-461c-9f8a-0d46dd079b5e)

**Comment by rpiedev** [comment]
Are you on the latest version of Lethal Company?
Does this affect the functionality of the mod?
I think I know why it says v1.4 and v1.3 might be my bad but the error concerns me, I haven't seen it on my end.

**Comment by MaStErDias** [comment]
I don’t know about the person above who uses wlakie use, but I play pirate version 45.1 with mods with friends and Steam 45.2 without mods. Do you think the problem is in the patch? (Google translate)

**Comment by JordinatorP** [comment]
same here, Pirated version and the current state of this mod do not work together. These are the only 2 mods that do not work. (Flashlight and Walkie) For reasons unknown as of now

**Comment by rpiedev** [comment]
That error should only appear if the version being used does not have the Key Remap Panel, since these mods are the only ones that use it as of now. 

@JordinatorP Can you message me on discord @rrpie . I want to get a good look at why this might be happening

**Comment by rpiedev** [comment]
Thank you to @JordinatorP for helping with this.

The issue seems to be caused because the cracked version is missing some features that the latest steam version has. If you want to fix, make sure the Assembly C Sharp file in the managed folder is the latest version from the game, it will not work otherwise as it stands.
