### ISSUE TITLE
Can't bind on controllers

### ISSUE THREAD

**Issue by LanHikariDS** [redassser/Lc-Flashlight#5]
Despite the entry being under Controllers, it doesn't actually detect controller inputs when attempting to rebind.

**Comment by rpiedev** [comment]
The controls for the mods are technically uncategorized, which happens to be at the bottom with the controller ones! I plan on making a separate category for modded controls and controller support as well, just have to figure those out...

**Comment by rpiedev** [comment]
Input Utils has a controller option, so its pretty nice
