### ISSUE TITLE
Can't see in game rebinds when using inputUtils API

### ISSUE THREAD

**Issue by KingKalua808** [redassser/Lc-Flashlight#6]
When you have LethalCompany InputUtils by Rune580 installed, the key binds for both your flashlight and walkie mods don't show up in the menus. Once I remove that mod, they show up again. 

Link to mod in question: https://thunderstore.io/c/lethal-company/p/Rune580/LethalCompany_InputUtils/

**Comment by rpiedev** [comment]
Ooooh, finally. I've been waiting for someone to make this API, almost made it myself. I want to use this API but I know some people use these flashlight and walkie mods on their own as just QoL. Not sure what to do. I'll see.

**Comment by rpiedev** [comment]
I ended up using it as a dependency, its pretty nice!
