### ISSUE TITLE
Flashlight still trigger by F when flashlight key is rebind to another key

### ISSUE THREAD

**Issue by coissay** [redassser/Lc-Flashlight#7]
The flashlight is still trigger by the F key alongside with the new rebinded key. The flashlight should only be triggered by the key defined in the settings.

For example i bind the flashlight to H then the flashlight is triggered by the F key and the H key.

**Comment by rpiedev** [comment]
I tried to recreate this issue but this wasn't happening to me. Remember there are 2 bindings, maybe you bound H in the controller section? Or maybe theres another mod that interferes, not sure! I'll close for now unless you can recreate.

**Comment by coissay** [comment]
That's what i also thought but you can't assign keyboard keys to the controller section.

Ill try to uninstall all mods and try again if i can trigger it again ill make another issue
