### ISSUE TITLE
The script could not be instantiated

### ISSUE THREAD

**Issue by flop25** [redassser/Lc-Flashlight#9]
Hello
thank you for such mod 
Unfortunately my friends and I never could have this mod and the walkie one to work. 
as you see there is that error returned:
![image](https://github.com/redassser/Lc-Flashlight/assets/736909/6574a549-a79d-408b-8e6b-233a34fb2349)

**Comment by rpiedev** [comment]
Do you have the dependency input utils installed?

**Comment by flop25** [comment]
Well well well
we really thought we had it BUT Thunderstore did not download the files. So it was listed but nothing actually
